// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = chrome.app;

  app.runtime.onLaunched.addListener(function() {
    return app.window.create('index.html', {
      defaultWidth: 800,
      minWidth: 600,
      defaultHeight: 500,
      minHeight: 500,
      id: 'chrome-notes'
    });
  });

}).call(this);
