// Generated by CoffeeScript 1.6.2
(function() {
  var Router, app;

  app = window.app;

  Router = Backbone.Router.extend({
    routes: {
      'folder/:id': 'folder',
      'note/:id': 'note',
      '': 'all'
    },
    folder: function(folderId) {
      var folderNotes, note, _i, _len, _results;

      folderNotes = app.Collection.Folders.get(folderId).rel('notes');
      app.AppEvent.trigger('hide:notes');
      if (folderNotes != null) {
        _results = [];
        for (_i = 0, _len = folderNotes.length; _i < _len; _i++) {
          note = folderNotes[_i];
          _results.push(note.view.show());
        }
        return _results;
      }
    },
    note: function(noteId) {
      var _ref;

      app.AppEvent.trigger('hide:notes');
      return (_ref = app.Collection.Notes.get(noteId).view) != null ? _ref.showFull() : void 0;
    },
    all: function() {
      return app.AppEvent.trigger('show:notes');
    }
  });

  app.Router = new Router;

  Backbone.history.start();

}).call(this);
