// Generated by CoffeeScript 1.6.2
(function() {
  var Folders, app;

  app = window.app;

  Folders = Backbone.Collection.extend({
    model: app.Model.Folder,
    type: 'folder',
    initialize: function() {
      return this.fetch();
    }
  });

  app.Collection.Folders = new Folders;

}).call(this);
