// Generated by CoffeeScript 1.6.2
(function() {
  var Notes, app;

  app = window.app;

  Notes = Backbone.Collection.extend({
    model: app.Model.Note,
    initialize: function() {
      return this.fetch();
    }
  });

  app.Collection.Notes = new Notes;

}).call(this);
