// Generated by CoffeeScript 1.6.2
(function() {
  var iterator;

  this.app = {
    Model: {},
    Collection: {},
    View: {},
    Mixin: {},
    Iterator: {}
  };

  iterator = (function() {
    return function() {
      var i;

      i = 0;
      return {
        next: function() {
          return i++;
        },
        get: function() {
          return i;
        },
        set: function(newI) {
          return i = newI;
        }
      };
    };
  })();

  this.app.Iterator.folder = iterator();

  this.app.Iterator.note = iterator();

  Backbone.Model.prototype.toJSON = function() {
    var _ref;

    return _.extend({}, _.clone(this.attributes, {
      id: (_ref = this.id) != null ? _ref : this.cid
    }));
  };

  this.$ = jQuery;

}).call(this);
