// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = window.app;

  app.View.Note = Backbone.View.extend({
    className: 'row-fluid',
    events: {
      'click .edit': 'renderForm',
      'click .delete': 'renderConfirmForm'
    },
    $notesWrapper: $('#notes'),
    $noteForm: $('#form-add-note'),
    $confirmModalForm: $('#form-note-confirm'),
    form: document.note_form,
    Templates: {
      noteItem: app.Template.Note.noteItem,
      noteForm: app.Template.Note.noteForm,
      noteConfirmForm: app.Template.Note.confirmForm,
      noteFull: app.Template.Note.full
    },
    initialize: function() {
      this.save = _.bind(this.save, this);
      this.destroy = _.bind(this.destroy, this);
      this.model.view = this;
      this.viewType = 'list';
      this.show();
      this.$noteForm.on('click', '.save-note', this.save);
      this.$confirmModalForm.on('click', '.delete', this.destroy);
      return this.listenEvents();
    },
    listenEvents: function() {
      this.listenTo(this.model, 'change:title change:body', this.renderListItem);
      this.listenTo(this.model, 'change:title change:body', this.renderFull);
      this.listenTo(this.model, 'remove', this.remove);
      this.listenTo(app.AppEvent, 'hide:notes', this.hide);
      this.listenTo(app.AppEvent, 'show:notes', this.show);
      return this;
    },
    destroy: function(event) {
      if (+event.target.dataset.id !== +this.model.id) {
        return;
      }
      this.model.collection.remove(this.model);
      this.$confirmModalForm.modal('hide');
      return this;
    },
    remove: function() {
      delete this.options.model;
      delete this.model.view;
      delete this.model;
      this.$noteForm.unbind('click', this.save);
      this.$confirmModalForm.unbind('click', this.destroy);
      return Backbone.View.prototype.remove.apply(this, arguments);
    },
    hide: function() {
      return this.$el.detach();
    },
    show: function() {
      this.viewType = 'list';
      return this.renderListItem().$el.appendTo(this.$notesWrapper);
    },
    showFull: function() {
      this.viewType = 'full';
      return this.renderFull().$el.appendTo(this.$notesWrapper);
    },
    renderForm: function() {
      return this.form.innerHTML = this.Templates.noteForm(_.extend({}, this.model.toJSON(), {
        folders: app.Collection.Folders.toJSON()
      }));
    },
    renderConfirmForm: function() {
      return this.$confirmModalForm.html(this.Templates.noteConfirmForm(this.model.toJSON()));
    },
    save: function(event) {
      if (+event.target.dataset.id !== +this.model.id) {
        return;
      }
      this.model.save({
        title: this.form.title.value,
        body: this.form.body.value,
        folder_id: this.form.folder.value
      });
      return this.$noteForm.modal('hide');
    },
    renderListItem: function() {
      if (this.viewType === 'list') {
        this.$el.html(this.Templates.noteItem(this.model.toJSON()));
      }
      return this;
    },
    renderFull: function() {
      if (this.viewType === 'full') {
        this.$el.html(this.Templates.noteFull(this.model.toJSON()));
      }
      return this;
    }
  });

}).call(this);
