// Generated by CoffeeScript 1.6.2
(function() {
  var Folder, app;

  app = window.app;

  Folder = Backbone.Model.extend({
    defaults: function() {
      return {
        title: '',
        notes: {}
      };
    },
    initialize: function() {
      var _ref;

      if ((_ref = this.cid) == null) {
        this.cid = app.Iterator.folder.next();
      }
      new app.View.Folder({
        model: this
      });
      return this.listenEvents();
    },
    listenEvents: function() {
      this.on('remove', this.destroy, this);
      return this.on('remove', this.clear, this);
    }
  });

  Folder.prototype.hasMany = function() {
    return {
      notes: {
        collection: app.Collection.Notes,
        id: 'folder_id',
        filter: function(note) {
          return +note.get('folder_id') === +this.id;
        }
      }
    };
  };

  app.Model.Folder = Folder;

}).call(this);
