// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = this.app;

  app.Model.Note = Backbone.Model.extend({
    defaults: function() {
      return {
        title: '',
        body: ''
      };
    },
    initialize: function() {
      var _ref;

      if ((_ref = this.id) == null) {
        this.id = app.Iterator.note.next();
      }
      new app.View.Note({
        model: this
      });
      return this.listenEvents();
    },
    listenEvents: function() {
      this.on('all', function(event) {
        return console.log(event, 'Note event');
      });
      this.on('remove', this.destroy, this);
      return this.on('remove', this.clear, this);
    }
  });

  app.Model.prototype.belongsTo = function() {
    return {
      folder: app.Collection.Folders
    };
  };

}).call(this);
